// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="array_io_array_io,hls_ip_2022_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.242000,HLS_SYN_LAT=9,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1106,HLS_SYN_LUT=2311,HLS_VERSION=2022_1}" *)

module array_io (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        d_o_0_address0,
        d_o_0_ce0,
        d_o_0_we0,
        d_o_0_d0,
        d_o_0_address1,
        d_o_0_ce1,
        d_o_0_we1,
        d_o_0_d1,
        d_o_1_address0,
        d_o_1_ce0,
        d_o_1_we0,
        d_o_1_d0,
        d_o_1_address1,
        d_o_1_ce1,
        d_o_1_we1,
        d_o_1_d1,
        d_o_2_address0,
        d_o_2_ce0,
        d_o_2_we0,
        d_o_2_d0,
        d_o_2_address1,
        d_o_2_ce1,
        d_o_2_we1,
        d_o_2_d1,
        d_o_3_address0,
        d_o_3_ce0,
        d_o_3_we0,
        d_o_3_d0,
        d_o_3_address1,
        d_o_3_ce1,
        d_o_3_we1,
        d_o_3_d1,
        d_i_0_address0,
        d_i_0_ce0,
        d_i_0_q0,
        d_i_0_address1,
        d_i_0_ce1,
        d_i_0_q1,
        d_i_1_address0,
        d_i_1_ce0,
        d_i_1_q0,
        d_i_1_address1,
        d_i_1_ce1,
        d_i_1_q1
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] d_o_0_address0;
output   d_o_0_ce0;
output   d_o_0_we0;
output  [15:0] d_o_0_d0;
output  [2:0] d_o_0_address1;
output   d_o_0_ce1;
output   d_o_0_we1;
output  [15:0] d_o_0_d1;
output  [2:0] d_o_1_address0;
output   d_o_1_ce0;
output   d_o_1_we0;
output  [15:0] d_o_1_d0;
output  [2:0] d_o_1_address1;
output   d_o_1_ce1;
output   d_o_1_we1;
output  [15:0] d_o_1_d1;
output  [2:0] d_o_2_address0;
output   d_o_2_ce0;
output   d_o_2_we0;
output  [15:0] d_o_2_d0;
output  [2:0] d_o_2_address1;
output   d_o_2_ce1;
output   d_o_2_we1;
output  [15:0] d_o_2_d1;
output  [2:0] d_o_3_address0;
output   d_o_3_ce0;
output   d_o_3_we0;
output  [15:0] d_o_3_d0;
output  [2:0] d_o_3_address1;
output   d_o_3_ce1;
output   d_o_3_we1;
output  [15:0] d_o_3_d1;
output  [3:0] d_i_0_address0;
output   d_i_0_ce0;
input  [15:0] d_i_0_q0;
output  [3:0] d_i_0_address1;
output   d_i_0_ce1;
input  [15:0] d_i_0_q1;
output  [3:0] d_i_1_address0;
output   d_i_1_ce0;
input  [15:0] d_i_1_q0;
output  [3:0] d_i_1_address1;
output   d_i_1_ce1;
input  [15:0] d_i_1_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[2:0] d_o_0_address0;
reg d_o_0_ce0;
reg d_o_0_we0;
reg[15:0] d_o_0_d0;
reg[2:0] d_o_0_address1;
reg d_o_0_ce1;
reg d_o_0_we1;
reg[15:0] d_o_0_d1;
reg[2:0] d_o_1_address0;
reg d_o_1_ce0;
reg d_o_1_we0;
reg[15:0] d_o_1_d0;
reg[2:0] d_o_1_address1;
reg d_o_1_ce1;
reg d_o_1_we1;
reg[15:0] d_o_1_d1;
reg[2:0] d_o_2_address0;
reg d_o_2_ce0;
reg d_o_2_we0;
reg[15:0] d_o_2_d0;
reg[2:0] d_o_2_address1;
reg d_o_2_ce1;
reg d_o_2_we1;
reg[15:0] d_o_2_d1;
reg[2:0] d_o_3_address0;
reg d_o_3_ce0;
reg d_o_3_we0;
reg[15:0] d_o_3_d0;
reg[2:0] d_o_3_address1;
reg d_o_3_ce1;
reg d_o_3_we1;
reg[15:0] d_o_3_d1;
reg[3:0] d_i_0_address0;
reg d_i_0_ce0;
reg[3:0] d_i_0_address1;
reg d_i_0_ce1;
reg[3:0] d_i_1_address0;
reg d_i_1_ce0;
reg[3:0] d_i_1_address1;
reg d_i_1_ce1;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] acc_0;
reg   [31:0] acc_1;
reg   [31:0] acc_2;
reg   [31:0] acc_3;
reg   [31:0] acc_4;
reg   [31:0] acc_5;
reg   [31:0] acc_6;
reg   [31:0] acc_7;
reg  signed [15:0] d_i_0_load_reg_1354;
wire    ap_CS_fsm_state2;
reg  signed [15:0] d_i_1_load_reg_1360;
reg  signed [15:0] d_i_0_load_1_reg_1366;
reg  signed [15:0] d_i_1_load_1_reg_1372;
reg  signed [15:0] d_i_0_load_2_reg_1398;
wire    ap_CS_fsm_state3;
reg  signed [15:0] d_i_1_load_2_reg_1404;
reg  signed [15:0] d_i_0_load_3_reg_1410;
reg  signed [15:0] d_i_1_load_3_reg_1416;
reg  signed [15:0] d_i_0_load_4_reg_1442;
wire    ap_CS_fsm_state4;
reg  signed [15:0] d_i_1_load_4_reg_1448;
reg  signed [15:0] d_i_0_load_5_reg_1454;
reg  signed [15:0] d_i_1_load_5_reg_1460;
reg  signed [15:0] d_i_0_load_6_reg_1486;
wire    ap_CS_fsm_state5;
reg  signed [15:0] d_i_1_load_6_reg_1492;
reg  signed [15:0] d_i_0_load_7_reg_1498;
reg  signed [15:0] d_i_1_load_7_reg_1504;
reg  signed [15:0] d_i_0_load_8_reg_1530;
wire    ap_CS_fsm_state6;
reg  signed [15:0] d_i_1_load_8_reg_1536;
reg  signed [15:0] d_i_0_load_9_reg_1542;
reg  signed [15:0] d_i_1_load_9_reg_1548;
wire   [15:0] add_ln69_8_fu_818_p2;
reg   [15:0] add_ln69_8_reg_1598;
wire    ap_CS_fsm_state7;
wire   [15:0] add_ln69_9_fu_823_p2;
reg   [15:0] add_ln69_9_reg_1604;
wire   [15:0] add_ln69_10_fu_828_p2;
reg   [15:0] add_ln69_10_reg_1610;
wire   [15:0] add_ln69_11_fu_833_p2;
reg   [15:0] add_ln69_11_reg_1616;
wire   [15:0] add_ln69_12_fu_838_p2;
reg   [15:0] add_ln69_12_reg_1622;
wire   [15:0] add_ln69_13_fu_843_p2;
reg   [15:0] add_ln69_13_reg_1628;
wire   [15:0] add_ln69_14_fu_848_p2;
reg   [15:0] add_ln69_14_reg_1634;
wire   [15:0] add_ln69_15_fu_853_p2;
reg   [15:0] add_ln69_15_reg_1640;
reg  signed [15:0] d_i_0_load_10_reg_1646;
reg  signed [15:0] d_i_1_load_10_reg_1652;
reg  signed [15:0] d_i_0_load_11_reg_1658;
reg  signed [15:0] d_i_1_load_11_reg_1664;
wire   [15:0] add_ln69_16_fu_861_p2;
reg   [15:0] add_ln69_16_reg_1690;
wire    ap_CS_fsm_state8;
wire   [15:0] add_ln69_17_fu_868_p2;
reg   [15:0] add_ln69_17_reg_1695;
wire   [15:0] add_ln69_18_fu_875_p2;
reg   [15:0] add_ln69_18_reg_1700;
wire   [15:0] add_ln69_19_fu_882_p2;
reg   [15:0] add_ln69_19_reg_1705;
wire   [16:0] add_ln67_1_fu_890_p2;
reg   [16:0] add_ln67_1_reg_1710;
wire   [15:0] add_ln69_24_fu_896_p2;
reg   [15:0] add_ln69_24_reg_1715;
wire   [16:0] add_ln67_5_fu_906_p2;
reg   [16:0] add_ln67_5_reg_1720;
wire   [15:0] add_ln69_25_fu_912_p2;
reg   [15:0] add_ln69_25_reg_1725;
wire   [16:0] add_ln67_9_fu_922_p2;
reg   [16:0] add_ln67_9_reg_1730;
wire   [15:0] add_ln69_26_fu_928_p2;
reg   [15:0] add_ln69_26_reg_1735;
wire   [16:0] add_ln67_13_fu_938_p2;
reg   [16:0] add_ln67_13_reg_1740;
wire   [15:0] add_ln69_27_fu_944_p2;
reg   [15:0] add_ln69_27_reg_1745;
wire   [16:0] add_ln67_17_fu_1130_p2;
reg   [16:0] add_ln67_17_reg_1770;
wire    ap_CS_fsm_state9;
wire   [15:0] add_ln69_28_fu_1136_p2;
reg   [15:0] add_ln69_28_reg_1775;
wire   [16:0] add_ln67_21_fu_1146_p2;
reg   [16:0] add_ln67_21_reg_1780;
wire   [15:0] add_ln69_29_fu_1152_p2;
reg   [15:0] add_ln69_29_reg_1785;
wire   [16:0] add_ln67_25_fu_1162_p2;
reg   [16:0] add_ln67_25_reg_1790;
wire   [15:0] add_ln69_30_fu_1168_p2;
reg   [15:0] add_ln69_30_reg_1795;
wire   [16:0] add_ln67_29_fu_1178_p2;
reg   [16:0] add_ln67_29_reg_1800;
wire   [15:0] add_ln69_31_fu_1184_p2;
reg   [15:0] add_ln69_31_reg_1805;
wire    ap_CS_fsm_state10;
wire   [31:0] temp_fu_1024_p2;
wire   [31:0] temp_1_fu_1054_p2;
wire   [31:0] temp_2_fu_1084_p2;
wire   [31:0] temp_3_fu_1114_p2;
wire   [31:0] temp_4_fu_1232_p2;
wire   [31:0] temp_5_fu_1262_p2;
wire   [31:0] temp_6_fu_1292_p2;
wire   [31:0] temp_7_fu_1322_p2;
wire   [15:0] add_ln69_fu_714_p2;
wire   [15:0] add_ln69_4_fu_770_p2;
wire   [15:0] add_ln69_20_fu_977_p2;
wire   [15:0] add_ln69_1_fu_728_p2;
wire   [15:0] add_ln69_5_fu_784_p2;
wire   [15:0] add_ln69_21_fu_985_p2;
wire   [15:0] add_ln69_2_fu_742_p2;
wire   [15:0] add_ln69_6_fu_798_p2;
wire   [15:0] add_ln69_22_fu_993_p2;
wire   [15:0] add_ln69_3_fu_756_p2;
wire   [15:0] add_ln69_7_fu_812_p2;
wire   [15:0] add_ln69_23_fu_1001_p2;
wire   [15:0] trunc_ln67_fu_710_p1;
wire   [15:0] trunc_ln67_1_fu_724_p1;
wire   [15:0] trunc_ln67_2_fu_738_p1;
wire   [15:0] trunc_ln67_3_fu_752_p1;
wire   [15:0] trunc_ln67_4_fu_766_p1;
wire   [15:0] trunc_ln67_5_fu_780_p1;
wire   [15:0] trunc_ln67_6_fu_794_p1;
wire   [15:0] trunc_ln67_7_fu_808_p1;
wire  signed [15:0] sext_ln67_8_fu_886_p0;
wire  signed [16:0] sext_ln69_8_fu_858_p1;
wire  signed [16:0] sext_ln67_8_fu_886_p1;
wire  signed [15:0] add_ln69_24_fu_896_p0;
wire  signed [15:0] sext_ln67_11_fu_902_p0;
wire  signed [16:0] sext_ln69_9_fu_865_p1;
wire  signed [16:0] sext_ln67_11_fu_902_p1;
wire  signed [15:0] add_ln69_25_fu_912_p0;
wire  signed [15:0] sext_ln67_14_fu_918_p0;
wire  signed [16:0] sext_ln69_10_fu_872_p1;
wire  signed [16:0] sext_ln67_14_fu_918_p1;
wire  signed [15:0] add_ln69_26_fu_928_p0;
wire  signed [15:0] sext_ln67_17_fu_934_p0;
wire  signed [16:0] sext_ln69_11_fu_879_p1;
wire  signed [16:0] sext_ln67_17_fu_934_p1;
wire  signed [15:0] add_ln69_27_fu_944_p0;
wire  signed [31:0] sext_ln67_fu_950_p1;
wire  signed [17:0] sext_ln67_9_fu_1011_p1;
wire  signed [17:0] sext_ln69_fu_962_p1;
wire   [17:0] add_ln67_2_fu_1014_p2;
wire  signed [31:0] sext_ln67_10_fu_1020_p1;
wire   [31:0] add_ln67_fu_1006_p2;
wire  signed [31:0] sext_ln67_1_fu_953_p1;
wire  signed [17:0] sext_ln67_12_fu_1041_p1;
wire  signed [17:0] sext_ln69_1_fu_965_p1;
wire   [17:0] add_ln67_6_fu_1044_p2;
wire  signed [31:0] sext_ln67_13_fu_1050_p1;
wire   [31:0] add_ln67_4_fu_1036_p2;
wire  signed [31:0] sext_ln67_2_fu_956_p1;
wire  signed [17:0] sext_ln67_15_fu_1071_p1;
wire  signed [17:0] sext_ln69_2_fu_968_p1;
wire   [17:0] add_ln67_10_fu_1074_p2;
wire  signed [31:0] sext_ln67_16_fu_1080_p1;
wire   [31:0] add_ln67_8_fu_1066_p2;
wire  signed [31:0] sext_ln67_3_fu_959_p1;
wire  signed [17:0] sext_ln67_18_fu_1101_p1;
wire  signed [17:0] sext_ln69_3_fu_971_p1;
wire   [17:0] add_ln67_14_fu_1104_p2;
wire  signed [31:0] sext_ln67_19_fu_1110_p1;
wire   [31:0] add_ln67_12_fu_1096_p2;
wire  signed [15:0] sext_ln67_20_fu_1126_p0;
wire  signed [16:0] sext_ln69_12_fu_974_p1;
wire  signed [16:0] sext_ln67_20_fu_1126_p1;
wire  signed [15:0] add_ln69_28_fu_1136_p0;
wire  signed [15:0] sext_ln67_23_fu_1142_p0;
wire  signed [16:0] sext_ln69_13_fu_982_p1;
wire  signed [16:0] sext_ln67_23_fu_1142_p1;
wire  signed [15:0] add_ln69_29_fu_1152_p0;
wire  signed [15:0] sext_ln67_26_fu_1158_p0;
wire  signed [16:0] sext_ln69_14_fu_990_p1;
wire  signed [16:0] sext_ln67_26_fu_1158_p1;
wire  signed [15:0] add_ln69_30_fu_1168_p0;
wire  signed [15:0] sext_ln67_29_fu_1174_p0;
wire  signed [16:0] sext_ln69_15_fu_998_p1;
wire  signed [16:0] sext_ln67_29_fu_1174_p1;
wire  signed [15:0] add_ln69_31_fu_1184_p0;
wire  signed [31:0] sext_ln67_4_fu_1190_p1;
wire  signed [17:0] sext_ln67_21_fu_1219_p1;
wire  signed [17:0] sext_ln69_4_fu_1202_p1;
wire   [17:0] add_ln67_18_fu_1222_p2;
wire  signed [31:0] sext_ln67_22_fu_1228_p1;
wire   [31:0] add_ln67_16_fu_1214_p2;
wire  signed [31:0] sext_ln67_5_fu_1193_p1;
wire  signed [17:0] sext_ln67_24_fu_1249_p1;
wire  signed [17:0] sext_ln69_5_fu_1205_p1;
wire   [17:0] add_ln67_22_fu_1252_p2;
wire  signed [31:0] sext_ln67_25_fu_1258_p1;
wire   [31:0] add_ln67_20_fu_1244_p2;
wire  signed [31:0] sext_ln67_6_fu_1196_p1;
wire  signed [17:0] sext_ln67_27_fu_1279_p1;
wire  signed [17:0] sext_ln69_6_fu_1208_p1;
wire   [17:0] add_ln67_26_fu_1282_p2;
wire  signed [31:0] sext_ln67_28_fu_1288_p1;
wire   [31:0] add_ln67_24_fu_1274_p2;
wire  signed [31:0] sext_ln67_7_fu_1199_p1;
wire  signed [17:0] sext_ln67_30_fu_1309_p1;
wire  signed [17:0] sext_ln69_7_fu_1211_p1;
wire   [17:0] add_ln67_30_fu_1312_p2;
wire  signed [31:0] sext_ln67_31_fu_1318_p1;
wire   [31:0] add_ln67_28_fu_1304_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 acc_0 = 32'd0;
#0 acc_1 = 32'd0;
#0 acc_2 = 32'd0;
#0 acc_3 = 32'd0;
#0 acc_4 = 32'd0;
#0 acc_5 = 32'd0;
#0 acc_6 = 32'd0;
#0 acc_7 = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        acc_0 <= temp_fu_1024_p2;
        acc_1 <= temp_1_fu_1054_p2;
        acc_2 <= temp_2_fu_1084_p2;
        acc_3 <= temp_3_fu_1114_p2;
        add_ln67_17_reg_1770 <= add_ln67_17_fu_1130_p2;
        add_ln67_21_reg_1780 <= add_ln67_21_fu_1146_p2;
        add_ln67_25_reg_1790 <= add_ln67_25_fu_1162_p2;
        add_ln67_29_reg_1800 <= add_ln67_29_fu_1178_p2;
        add_ln69_28_reg_1775 <= add_ln69_28_fu_1136_p2;
        add_ln69_29_reg_1785 <= add_ln69_29_fu_1152_p2;
        add_ln69_30_reg_1795 <= add_ln69_30_fu_1168_p2;
        add_ln69_31_reg_1805 <= add_ln69_31_fu_1184_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        acc_4 <= temp_4_fu_1232_p2;
        acc_5 <= temp_5_fu_1262_p2;
        acc_6 <= temp_6_fu_1292_p2;
        acc_7 <= temp_7_fu_1322_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln67_13_reg_1740 <= add_ln67_13_fu_938_p2;
        add_ln67_1_reg_1710 <= add_ln67_1_fu_890_p2;
        add_ln67_5_reg_1720 <= add_ln67_5_fu_906_p2;
        add_ln67_9_reg_1730 <= add_ln67_9_fu_922_p2;
        add_ln69_16_reg_1690 <= add_ln69_16_fu_861_p2;
        add_ln69_17_reg_1695 <= add_ln69_17_fu_868_p2;
        add_ln69_18_reg_1700 <= add_ln69_18_fu_875_p2;
        add_ln69_19_reg_1705 <= add_ln69_19_fu_882_p2;
        add_ln69_24_reg_1715 <= add_ln69_24_fu_896_p2;
        add_ln69_25_reg_1725 <= add_ln69_25_fu_912_p2;
        add_ln69_26_reg_1735 <= add_ln69_26_fu_928_p2;
        add_ln69_27_reg_1745 <= add_ln69_27_fu_944_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln69_10_reg_1610 <= add_ln69_10_fu_828_p2;
        add_ln69_11_reg_1616 <= add_ln69_11_fu_833_p2;
        add_ln69_12_reg_1622 <= add_ln69_12_fu_838_p2;
        add_ln69_13_reg_1628 <= add_ln69_13_fu_843_p2;
        add_ln69_14_reg_1634 <= add_ln69_14_fu_848_p2;
        add_ln69_15_reg_1640 <= add_ln69_15_fu_853_p2;
        add_ln69_8_reg_1598 <= add_ln69_8_fu_818_p2;
        add_ln69_9_reg_1604 <= add_ln69_9_fu_823_p2;
        d_i_0_load_10_reg_1646 <= d_i_0_q1;
        d_i_0_load_11_reg_1658 <= d_i_0_q0;
        d_i_1_load_10_reg_1652 <= d_i_1_q1;
        d_i_1_load_11_reg_1664 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_0_load_1_reg_1366 <= d_i_0_q0;
        d_i_0_load_reg_1354 <= d_i_0_q1;
        d_i_1_load_1_reg_1372 <= d_i_1_q0;
        d_i_1_load_reg_1360 <= d_i_1_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_0_load_2_reg_1398 <= d_i_0_q1;
        d_i_0_load_3_reg_1410 <= d_i_0_q0;
        d_i_1_load_2_reg_1404 <= d_i_1_q1;
        d_i_1_load_3_reg_1416 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_0_load_4_reg_1442 <= d_i_0_q1;
        d_i_0_load_5_reg_1454 <= d_i_0_q0;
        d_i_1_load_4_reg_1448 <= d_i_1_q1;
        d_i_1_load_5_reg_1460 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_0_load_6_reg_1486 <= d_i_0_q1;
        d_i_0_load_7_reg_1498 <= d_i_0_q0;
        d_i_1_load_6_reg_1492 <= d_i_1_q1;
        d_i_1_load_7_reg_1504 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_0_load_8_reg_1530 <= d_i_0_q1;
        d_i_0_load_9_reg_1542 <= d_i_0_q0;
        d_i_1_load_8_reg_1536 <= d_i_1_q1;
        d_i_1_load_9_reg_1548 <= d_i_1_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_0_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_0_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_0_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_0_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_0_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_0_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_0_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_0_address0 = 64'd1;
    end else begin
        d_i_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_0_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_0_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_0_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_0_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_0_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_0_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_0_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_0_address1 = 64'd0;
    end else begin
        d_i_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_0_ce0 = 1'b1;
    end else begin
        d_i_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_0_ce1 = 1'b1;
    end else begin
        d_i_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_1_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_1_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_1_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_1_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_1_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_1_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_1_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_1_address0 = 64'd1;
    end else begin
        d_i_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_1_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_1_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_1_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_1_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_1_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_1_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_1_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_1_address1 = 64'd0;
    end else begin
        d_i_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_1_ce0 = 1'b1;
    end else begin
        d_i_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_i_1_ce1 = 1'b1;
    end else begin
        d_i_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_0_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_0_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_0_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_0_address0 = 64'd1;
    end else begin
        d_o_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_0_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_0_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_0_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_0_address1 = 64'd0;
    end else begin
        d_o_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_0_ce0 = 1'b1;
    end else begin
        d_o_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_0_ce1 = 1'b1;
    end else begin
        d_o_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_0_d0 = add_ln69_28_reg_1775;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_0_d0 = add_ln69_20_fu_977_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_0_d0 = add_ln69_12_reg_1622;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_0_d0 = add_ln69_4_fu_770_p2;
    end else begin
        d_o_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_0_d1 = add_ln69_24_reg_1715;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_0_d1 = add_ln69_16_reg_1690;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_0_d1 = add_ln69_8_reg_1598;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_0_d1 = add_ln69_fu_714_p2;
    end else begin
        d_o_0_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_0_we0 = 1'b1;
    end else begin
        d_o_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_0_we1 = 1'b1;
    end else begin
        d_o_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_1_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_1_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_1_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_1_address0 = 64'd1;
    end else begin
        d_o_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_1_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_1_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_1_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_1_address1 = 64'd0;
    end else begin
        d_o_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_1_ce0 = 1'b1;
    end else begin
        d_o_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_1_ce1 = 1'b1;
    end else begin
        d_o_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_1_d0 = add_ln69_29_reg_1785;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_1_d0 = add_ln69_21_fu_985_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_1_d0 = add_ln69_13_reg_1628;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_1_d0 = add_ln69_5_fu_784_p2;
    end else begin
        d_o_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_1_d1 = add_ln69_25_reg_1725;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_1_d1 = add_ln69_17_reg_1695;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_1_d1 = add_ln69_9_reg_1604;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_1_d1 = add_ln69_1_fu_728_p2;
    end else begin
        d_o_1_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_1_we0 = 1'b1;
    end else begin
        d_o_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_1_we1 = 1'b1;
    end else begin
        d_o_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_2_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_2_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_2_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_2_address0 = 64'd1;
    end else begin
        d_o_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_2_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_2_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_2_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_2_address1 = 64'd0;
    end else begin
        d_o_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_2_ce0 = 1'b1;
    end else begin
        d_o_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_2_ce1 = 1'b1;
    end else begin
        d_o_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_2_d0 = add_ln69_30_reg_1795;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_2_d0 = add_ln69_22_fu_993_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_2_d0 = add_ln69_14_reg_1634;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_2_d0 = add_ln69_6_fu_798_p2;
    end else begin
        d_o_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_2_d1 = add_ln69_26_reg_1735;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_2_d1 = add_ln69_18_reg_1700;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_2_d1 = add_ln69_10_reg_1610;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_2_d1 = add_ln69_2_fu_742_p2;
    end else begin
        d_o_2_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_2_we0 = 1'b1;
    end else begin
        d_o_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_2_we1 = 1'b1;
    end else begin
        d_o_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_3_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_3_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_3_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_3_address0 = 64'd1;
    end else begin
        d_o_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_3_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_3_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_3_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_3_address1 = 64'd0;
    end else begin
        d_o_3_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_3_ce0 = 1'b1;
    end else begin
        d_o_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_3_ce1 = 1'b1;
    end else begin
        d_o_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_3_d0 = add_ln69_31_reg_1805;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_3_d0 = add_ln69_23_fu_1001_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_3_d0 = add_ln69_15_reg_1640;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_3_d0 = add_ln69_7_fu_812_p2;
    end else begin
        d_o_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_3_d1 = add_ln69_27_reg_1745;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_3_d1 = add_ln69_19_reg_1705;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_3_d1 = add_ln69_11_reg_1616;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_3_d1 = add_ln69_3_fu_756_p2;
    end else begin
        d_o_3_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_3_we0 = 1'b1;
    end else begin
        d_o_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        d_o_3_we1 = 1'b1;
    end else begin
        d_o_3_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_10_fu_1074_p2 = ($signed(sext_ln67_15_fu_1071_p1) + $signed(sext_ln69_2_fu_968_p1));

assign add_ln67_12_fu_1096_p2 = ($signed(acc_3) + $signed(sext_ln67_3_fu_959_p1));

assign add_ln67_13_fu_938_p2 = ($signed(sext_ln69_11_fu_879_p1) + $signed(sext_ln67_17_fu_934_p1));

assign add_ln67_14_fu_1104_p2 = ($signed(sext_ln67_18_fu_1101_p1) + $signed(sext_ln69_3_fu_971_p1));

assign add_ln67_16_fu_1214_p2 = ($signed(acc_4) + $signed(sext_ln67_4_fu_1190_p1));

assign add_ln67_17_fu_1130_p2 = ($signed(sext_ln69_12_fu_974_p1) + $signed(sext_ln67_20_fu_1126_p1));

assign add_ln67_18_fu_1222_p2 = ($signed(sext_ln67_21_fu_1219_p1) + $signed(sext_ln69_4_fu_1202_p1));

assign add_ln67_1_fu_890_p2 = ($signed(sext_ln69_8_fu_858_p1) + $signed(sext_ln67_8_fu_886_p1));

assign add_ln67_20_fu_1244_p2 = ($signed(acc_5) + $signed(sext_ln67_5_fu_1193_p1));

assign add_ln67_21_fu_1146_p2 = ($signed(sext_ln69_13_fu_982_p1) + $signed(sext_ln67_23_fu_1142_p1));

assign add_ln67_22_fu_1252_p2 = ($signed(sext_ln67_24_fu_1249_p1) + $signed(sext_ln69_5_fu_1205_p1));

assign add_ln67_24_fu_1274_p2 = ($signed(acc_6) + $signed(sext_ln67_6_fu_1196_p1));

assign add_ln67_25_fu_1162_p2 = ($signed(sext_ln69_14_fu_990_p1) + $signed(sext_ln67_26_fu_1158_p1));

assign add_ln67_26_fu_1282_p2 = ($signed(sext_ln67_27_fu_1279_p1) + $signed(sext_ln69_6_fu_1208_p1));

assign add_ln67_28_fu_1304_p2 = ($signed(acc_7) + $signed(sext_ln67_7_fu_1199_p1));

assign add_ln67_29_fu_1178_p2 = ($signed(sext_ln69_15_fu_998_p1) + $signed(sext_ln67_29_fu_1174_p1));

assign add_ln67_2_fu_1014_p2 = ($signed(sext_ln67_9_fu_1011_p1) + $signed(sext_ln69_fu_962_p1));

assign add_ln67_30_fu_1312_p2 = ($signed(sext_ln67_30_fu_1309_p1) + $signed(sext_ln69_7_fu_1211_p1));

assign add_ln67_4_fu_1036_p2 = ($signed(acc_1) + $signed(sext_ln67_1_fu_953_p1));

assign add_ln67_5_fu_906_p2 = ($signed(sext_ln69_9_fu_865_p1) + $signed(sext_ln67_11_fu_902_p1));

assign add_ln67_6_fu_1044_p2 = ($signed(sext_ln67_12_fu_1041_p1) + $signed(sext_ln69_1_fu_965_p1));

assign add_ln67_8_fu_1066_p2 = ($signed(acc_2) + $signed(sext_ln67_2_fu_956_p1));

assign add_ln67_9_fu_922_p2 = ($signed(sext_ln69_10_fu_872_p1) + $signed(sext_ln67_14_fu_918_p1));

assign add_ln67_fu_1006_p2 = ($signed(acc_0) + $signed(sext_ln67_fu_950_p1));

assign add_ln69_10_fu_828_p2 = ($signed(d_i_0_load_5_reg_1454) + $signed(add_ln69_2_fu_742_p2));

assign add_ln69_11_fu_833_p2 = ($signed(d_i_1_load_5_reg_1460) + $signed(add_ln69_3_fu_756_p2));

assign add_ln69_12_fu_838_p2 = ($signed(d_i_0_load_6_reg_1486) + $signed(add_ln69_4_fu_770_p2));

assign add_ln69_13_fu_843_p2 = ($signed(d_i_1_load_6_reg_1492) + $signed(add_ln69_5_fu_784_p2));

assign add_ln69_14_fu_848_p2 = ($signed(d_i_0_load_7_reg_1498) + $signed(add_ln69_6_fu_798_p2));

assign add_ln69_15_fu_853_p2 = ($signed(d_i_1_load_7_reg_1504) + $signed(add_ln69_7_fu_812_p2));

assign add_ln69_16_fu_861_p2 = ($signed(d_i_0_load_8_reg_1530) + $signed(add_ln69_8_reg_1598));

assign add_ln69_17_fu_868_p2 = ($signed(d_i_1_load_8_reg_1536) + $signed(add_ln69_9_reg_1604));

assign add_ln69_18_fu_875_p2 = ($signed(d_i_0_load_9_reg_1542) + $signed(add_ln69_10_reg_1610));

assign add_ln69_19_fu_882_p2 = ($signed(d_i_1_load_9_reg_1548) + $signed(add_ln69_11_reg_1616));

assign add_ln69_1_fu_728_p2 = ($signed(d_i_1_load_reg_1360) + $signed(trunc_ln67_1_fu_724_p1));

assign add_ln69_20_fu_977_p2 = ($signed(d_i_0_load_10_reg_1646) + $signed(add_ln69_12_reg_1622));

assign add_ln69_21_fu_985_p2 = ($signed(d_i_1_load_10_reg_1652) + $signed(add_ln69_13_reg_1628));

assign add_ln69_22_fu_993_p2 = ($signed(d_i_0_load_11_reg_1658) + $signed(add_ln69_14_reg_1634));

assign add_ln69_23_fu_1001_p2 = ($signed(d_i_1_load_11_reg_1664) + $signed(add_ln69_15_reg_1640));

assign add_ln69_24_fu_896_p0 = d_i_0_q1;

assign add_ln69_24_fu_896_p2 = ($signed(add_ln69_24_fu_896_p0) + $signed(add_ln69_16_fu_861_p2));

assign add_ln69_25_fu_912_p0 = d_i_1_q1;

assign add_ln69_25_fu_912_p2 = ($signed(add_ln69_25_fu_912_p0) + $signed(add_ln69_17_fu_868_p2));

assign add_ln69_26_fu_928_p0 = d_i_0_q0;

assign add_ln69_26_fu_928_p2 = ($signed(add_ln69_26_fu_928_p0) + $signed(add_ln69_18_fu_875_p2));

assign add_ln69_27_fu_944_p0 = d_i_1_q0;

assign add_ln69_27_fu_944_p2 = ($signed(add_ln69_27_fu_944_p0) + $signed(add_ln69_19_fu_882_p2));

assign add_ln69_28_fu_1136_p0 = d_i_0_q1;

assign add_ln69_28_fu_1136_p2 = ($signed(add_ln69_28_fu_1136_p0) + $signed(add_ln69_20_fu_977_p2));

assign add_ln69_29_fu_1152_p0 = d_i_1_q1;

assign add_ln69_29_fu_1152_p2 = ($signed(add_ln69_29_fu_1152_p0) + $signed(add_ln69_21_fu_985_p2));

assign add_ln69_2_fu_742_p2 = ($signed(d_i_0_load_1_reg_1366) + $signed(trunc_ln67_2_fu_738_p1));

assign add_ln69_30_fu_1168_p0 = d_i_0_q0;

assign add_ln69_30_fu_1168_p2 = ($signed(add_ln69_30_fu_1168_p0) + $signed(add_ln69_22_fu_993_p2));

assign add_ln69_31_fu_1184_p0 = d_i_1_q0;

assign add_ln69_31_fu_1184_p2 = ($signed(add_ln69_31_fu_1184_p0) + $signed(add_ln69_23_fu_1001_p2));

assign add_ln69_3_fu_756_p2 = ($signed(d_i_1_load_1_reg_1372) + $signed(trunc_ln67_3_fu_752_p1));

assign add_ln69_4_fu_770_p2 = ($signed(d_i_0_load_2_reg_1398) + $signed(trunc_ln67_4_fu_766_p1));

assign add_ln69_5_fu_784_p2 = ($signed(d_i_1_load_2_reg_1404) + $signed(trunc_ln67_5_fu_780_p1));

assign add_ln69_6_fu_798_p2 = ($signed(d_i_0_load_3_reg_1410) + $signed(trunc_ln67_6_fu_794_p1));

assign add_ln69_7_fu_812_p2 = ($signed(d_i_1_load_3_reg_1416) + $signed(trunc_ln67_7_fu_808_p1));

assign add_ln69_8_fu_818_p2 = ($signed(d_i_0_load_4_reg_1442) + $signed(add_ln69_fu_714_p2));

assign add_ln69_9_fu_823_p2 = ($signed(d_i_1_load_4_reg_1448) + $signed(add_ln69_1_fu_728_p2));

assign add_ln69_fu_714_p2 = ($signed(d_i_0_load_reg_1354) + $signed(trunc_ln67_fu_710_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign sext_ln67_10_fu_1020_p1 = $signed(add_ln67_2_fu_1014_p2);

assign sext_ln67_11_fu_902_p0 = d_i_1_q1;

assign sext_ln67_11_fu_902_p1 = sext_ln67_11_fu_902_p0;

assign sext_ln67_12_fu_1041_p1 = $signed(add_ln67_5_reg_1720);

assign sext_ln67_13_fu_1050_p1 = $signed(add_ln67_6_fu_1044_p2);

assign sext_ln67_14_fu_918_p0 = d_i_0_q0;

assign sext_ln67_14_fu_918_p1 = sext_ln67_14_fu_918_p0;

assign sext_ln67_15_fu_1071_p1 = $signed(add_ln67_9_reg_1730);

assign sext_ln67_16_fu_1080_p1 = $signed(add_ln67_10_fu_1074_p2);

assign sext_ln67_17_fu_934_p0 = d_i_1_q0;

assign sext_ln67_17_fu_934_p1 = sext_ln67_17_fu_934_p0;

assign sext_ln67_18_fu_1101_p1 = $signed(add_ln67_13_reg_1740);

assign sext_ln67_19_fu_1110_p1 = $signed(add_ln67_14_fu_1104_p2);

assign sext_ln67_1_fu_953_p1 = d_i_1_load_reg_1360;

assign sext_ln67_20_fu_1126_p0 = d_i_0_q1;

assign sext_ln67_20_fu_1126_p1 = sext_ln67_20_fu_1126_p0;

assign sext_ln67_21_fu_1219_p1 = $signed(add_ln67_17_reg_1770);

assign sext_ln67_22_fu_1228_p1 = $signed(add_ln67_18_fu_1222_p2);

assign sext_ln67_23_fu_1142_p0 = d_i_1_q1;

assign sext_ln67_23_fu_1142_p1 = sext_ln67_23_fu_1142_p0;

assign sext_ln67_24_fu_1249_p1 = $signed(add_ln67_21_reg_1780);

assign sext_ln67_25_fu_1258_p1 = $signed(add_ln67_22_fu_1252_p2);

assign sext_ln67_26_fu_1158_p0 = d_i_0_q0;

assign sext_ln67_26_fu_1158_p1 = sext_ln67_26_fu_1158_p0;

assign sext_ln67_27_fu_1279_p1 = $signed(add_ln67_25_reg_1790);

assign sext_ln67_28_fu_1288_p1 = $signed(add_ln67_26_fu_1282_p2);

assign sext_ln67_29_fu_1174_p0 = d_i_1_q0;

assign sext_ln67_29_fu_1174_p1 = sext_ln67_29_fu_1174_p0;

assign sext_ln67_2_fu_956_p1 = d_i_0_load_1_reg_1366;

assign sext_ln67_30_fu_1309_p1 = $signed(add_ln67_29_reg_1800);

assign sext_ln67_31_fu_1318_p1 = $signed(add_ln67_30_fu_1312_p2);

assign sext_ln67_3_fu_959_p1 = d_i_1_load_1_reg_1372;

assign sext_ln67_4_fu_1190_p1 = d_i_0_load_2_reg_1398;

assign sext_ln67_5_fu_1193_p1 = d_i_1_load_2_reg_1404;

assign sext_ln67_6_fu_1196_p1 = d_i_0_load_3_reg_1410;

assign sext_ln67_7_fu_1199_p1 = d_i_1_load_3_reg_1416;

assign sext_ln67_8_fu_886_p0 = d_i_0_q1;

assign sext_ln67_8_fu_886_p1 = sext_ln67_8_fu_886_p0;

assign sext_ln67_9_fu_1011_p1 = $signed(add_ln67_1_reg_1710);

assign sext_ln67_fu_950_p1 = d_i_0_load_reg_1354;

assign sext_ln69_10_fu_872_p1 = d_i_0_load_9_reg_1542;

assign sext_ln69_11_fu_879_p1 = d_i_1_load_9_reg_1548;

assign sext_ln69_12_fu_974_p1 = d_i_0_load_10_reg_1646;

assign sext_ln69_13_fu_982_p1 = d_i_1_load_10_reg_1652;

assign sext_ln69_14_fu_990_p1 = d_i_0_load_11_reg_1658;

assign sext_ln69_15_fu_998_p1 = d_i_1_load_11_reg_1664;

assign sext_ln69_1_fu_965_p1 = d_i_1_load_4_reg_1448;

assign sext_ln69_2_fu_968_p1 = d_i_0_load_5_reg_1454;

assign sext_ln69_3_fu_971_p1 = d_i_1_load_5_reg_1460;

assign sext_ln69_4_fu_1202_p1 = d_i_0_load_6_reg_1486;

assign sext_ln69_5_fu_1205_p1 = d_i_1_load_6_reg_1492;

assign sext_ln69_6_fu_1208_p1 = d_i_0_load_7_reg_1498;

assign sext_ln69_7_fu_1211_p1 = d_i_1_load_7_reg_1504;

assign sext_ln69_8_fu_858_p1 = d_i_0_load_8_reg_1530;

assign sext_ln69_9_fu_865_p1 = d_i_1_load_8_reg_1536;

assign sext_ln69_fu_962_p1 = d_i_0_load_4_reg_1442;

assign temp_1_fu_1054_p2 = ($signed(sext_ln67_13_fu_1050_p1) + $signed(add_ln67_4_fu_1036_p2));

assign temp_2_fu_1084_p2 = ($signed(sext_ln67_16_fu_1080_p1) + $signed(add_ln67_8_fu_1066_p2));

assign temp_3_fu_1114_p2 = ($signed(sext_ln67_19_fu_1110_p1) + $signed(add_ln67_12_fu_1096_p2));

assign temp_4_fu_1232_p2 = ($signed(sext_ln67_22_fu_1228_p1) + $signed(add_ln67_16_fu_1214_p2));

assign temp_5_fu_1262_p2 = ($signed(sext_ln67_25_fu_1258_p1) + $signed(add_ln67_20_fu_1244_p2));

assign temp_6_fu_1292_p2 = ($signed(sext_ln67_28_fu_1288_p1) + $signed(add_ln67_24_fu_1274_p2));

assign temp_7_fu_1322_p2 = ($signed(sext_ln67_31_fu_1318_p1) + $signed(add_ln67_28_fu_1304_p2));

assign temp_fu_1024_p2 = ($signed(sext_ln67_10_fu_1020_p1) + $signed(add_ln67_fu_1006_p2));

assign trunc_ln67_1_fu_724_p1 = acc_1[15:0];

assign trunc_ln67_2_fu_738_p1 = acc_2[15:0];

assign trunc_ln67_3_fu_752_p1 = acc_3[15:0];

assign trunc_ln67_4_fu_766_p1 = acc_4[15:0];

assign trunc_ln67_5_fu_780_p1 = acc_5[15:0];

assign trunc_ln67_6_fu_794_p1 = acc_6[15:0];

assign trunc_ln67_7_fu_808_p1 = acc_7[15:0];

assign trunc_ln67_fu_710_p1 = acc_0[15:0];

endmodule //array_io
